plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.paramount'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

ext {
    springCloudAwsVersion = '3.3.0'  // Boot 3.2.x ? 3.3.x ?? ??
    awsSdkVersion         = '2.25.15' // AWS SDK v2 ?? ?? ??
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    implementation 'com.github.ua-parser:uap-java:1.6.0'

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'                /*??? ??????? Redis ??*/
    implementation 'org.springframework.session:spring-session-data-redis'                  /*???? Redis? ??*/

    //security
    implementation 'org.springframework.boot:spring-boot-starter-security'                  /*??? ?? Spring Security ??*/
    implementation 'org.springframework.security:spring-security-core'                      /*??? ?? Spring Security ?? : ??? ?? ??? ???? ?? ???? ????*/
    implementation 'org.springframework.security:spring-security-config'                    /*??? ?? Spring Security ?? : ? ???? ???? ????? ??? ???? ?? ????*/
    implementation 'org.springframework.security:spring-security-web'                       /*??? ?? Spring Security ?? : ? ??????? ?? ??? ???? ?? ????*/

    /* ===== Spring Cloud AWS ===== */
    implementation platform('software.amazon.awssdk:bom:2.25.16') // 2025년 5월 기준 최신 BOM
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:auth'
    implementation 'software.amazon.awssdk:sts' // 권한 위임 시 필요

    /* ===== UTIL ===== */
    implementation 'commons-net:commons-net:3.10.0' // FTPClient (Apache Commons Net)
    implementation 'commons-io:commons-io:2.15.0'
    implementation 'org.apache.tika:tika-core:2.9.1'
    implementation 'org.apache.commons:commons-lang3:3.18.0'
    implementation 'org.jsoup:jsoup:1.18.1'

    /* === SFTP (자바에서 SSH/SFTP) === */
    implementation 'com.github.mwiede:jsch:0.2.16'             // 유지보수되는 JSch 포크
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'    // 권장(최신 키/암호군 호환성)


    /* ===== photo 생성 UTIL ===== */
    //implementation "org.bytedeco:opencv-platform:4.11.0-1.5.12"
    implementation 'org.openpnp:opencv:4.5.5-1'
    // ImageIO 보강(선택)
    implementation 'com.twelvemonkeys.imageio:imageio-core:3.10.1'
    implementation 'com.twelvemonkeys.imageio:imageio-jpeg:3.10.1'

    // 인스타그램 썸네일 생성시 사용
    implementation 'net.coobird:thumbnailator:0.4.20'


    /* === 키워드 추출 === */
    implementation 'com.github.shin285:KOMORAN:3.3.9'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'


    // 엑셀
    implementation 'org.apache.poi:poi-ooxml:5.2.5'

    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'p6spy:p6spy:3.9.1'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


    // 7.17 대신 8.x 버전을 사용하도록 설정
    //implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    //implementation 'co.elastic.clients:elasticsearch-java:8.15.0' // 8.x 최신 버전 권장

    // JSON(프로젝트에 이미 있으면 생략)
    implementation "com.fasterxml.jackson.core:jackson-databind"

}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE   // ?? INCLUDE, WARN
}



