# 페이징 개수
PAGE_LIST_SIZE_DEFAULT=20
PAGE_LIST_SIZE_30=30
PAGE_LIST_SIZE_11=11
PAGE_LIST_SIZE_10=10
PAGE_LIST_SIZE_1=1
PAGE_LIST_SIZE_3=3
PAGE_LIST_SIZE_4=4
PAGE_LIST_SIZE_5=5
PAGE_LIST_SIZE_7=7
PAGE_LIST_SIZE_8=8
PAGE_LIST_SIZE_9=9
PAGE_LIST_SIZE_ALL=1000
PAGE_BLOCK_COUNT_DEFAULT=10
PAGE_BLOCK_COUNT_5=5

#--------------------------------------------------------------------------------------------------------------
# USER_ROLE 별 접속권한
# 1 : 일반사용자
# 2 : 강사
# 3 : 매니져
# 9 : 관리자

#--------------------------------------------------------------------------------------------------------------
USER_ROLE={\
    1 : 'USER',\
    2 : 'LECTURER',\
    3 : 'MANAGER',\
    9 : 'ADMIN',\
   
}


# 4: 240308 공도윤 딜사이트S 부국장 - 고객지원 권한 부여 -> 하려다가 취소
# USER_ROLE_BY_INDIVIDUAL={\
#     4 : 'ROLE_SUPPORT_ADMIN'\
# }

#--------------------------------------------------------------------------------------------------------------
# 엑셀 다운로드 다운로드 가능 개월수
#--------------------------------------------------------------------------------------------------------------
DOWNLOAD_MAX_MONTHS=12

#--------------------------------------------------------------------------------------------------------------
# 사이트 기준 (system code)
# SYSTEM_CODE : D --> data center
#--------------------------------------------------------------------------------------------------------------
SYSTEM_CODE = D

#--------------------------------------------------------------------------------------------------------------
# 이메일 템플릿
# DORMANCY_UPCOMING :'mail_dormancy_upcoming',\                     : 휴면 예정 안내 메일
# DORMANCY_COMPLETE :'mail_dormancy_complete',\                     : 휴면 전환 안내 메일
# ACCOUNT_LEAVE_CONFIRM : 'mail_account_leave_confirm',\            : 회원 탈퇴 안내 메일
# PROMOTION_EXPIRE_UPCOMING : 'mail_promotion_expire_upcoming'\     : 프로모션 회원 프로모션 기간 종료 예정 안내 메일
#--------------------------------------------------------------------------------------------------------------
EMAIL_TEMPLATES={\
    DORMANCY_UPCOMING :'mail_dormancy_upcoming',\
    DORMANCY_COMPLETE :'mail_dormancy_complete',\
    ACCOUNT_LEAVE_CONFIRM : 'mail_account_leave_confirm',\
    PROMOTION_EXPIRE_UPCOMING : 'mail_promotion_expire_upcoming'\
}
