log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.dump.sql.maxlinelength=0 #sql문을 최대 몇 라인까지 출력할 것인지를 설정 0은 제한 없음(default)
# log4jdbc의 드라이브 클래스 설정 
log4jdbc.drivers=com.mysql.cj.jdbc.Driver 
log4jdbc.auto.load.popular.drivers=false
