realdriver=com.mysql.cj.jdbc.Driver

#Spring/logback 관리
appender=com.p6spy.engine.spy.appender.Slf4JLogger
#파일에 로그 남기기
#appender=com.p6spy.engine.spy.appender.FileLogger
#logfile=logs/spy.log


#logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(sqlSingleLine)
excludecategories=info,debug,result,resultset,batch,commit,rollback

executionThreshold=0
includeBindings=true
useNanoTime=false
databaseDialectDateFormat=yyyy-MM-dd HH:mm:ss


#  기존존 설정
#appender=com.p6spy.engine.spy.appender.Slf4JLogger
#logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat
#includeBindings=true